#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 120
#define LARGE_STATE_COUNT 28
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_STAR = 1,
  anon_sym_SLASH = 2,
  anon_sym_PERCENT = 3,
  anon_sym_PLUS = 4,
  anon_sym_DASH = 5,
  anon_sym_EQ_EQ = 6,
  anon_sym_BANG_EQ = 7,
  anon_sym_LT = 8,
  anon_sym_LT_EQ = 9,
  anon_sym_GT = 10,
  anon_sym_GT_EQ = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_let = 14,
  anon_sym_BANG = 15,
  anon_sym_EQ = 16,
  anon_sym_if = 17,
  anon_sym_else = 18,
  anon_sym_iter = 19,
  anon_sym_of = 20,
  anon_sym_PIPE = 21,
  anon_sym_DASH_GT = 22,
  anon_sym_LBRACK = 23,
  anon_sym_RBRACK = 24,
  sym_identifier = 25,
  sym_string = 26,
  sym_number = 27,
  sym_source_file = 28,
  sym_expr = 29,
  sym_binexpr = 30,
  sym_unaryexpr = 31,
  sym_block = 32,
  sym_let = 33,
  sym_if = 34,
  sym_iter = 35,
  sym_func = 36,
  sym__literal = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_func_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_let] = "let",
  [anon_sym_BANG] = "!",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_iter] = "iter",
  [anon_sym_of] = "of",
  [anon_sym_PIPE] = "|",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_expr] = "expr",
  [sym_binexpr] = "binexpr",
  [sym_unaryexpr] = "unaryexpr",
  [sym_block] = "block",
  [sym_let] = "let",
  [sym_if] = "if",
  [sym_iter] = "iter",
  [sym_func] = "func",
  [sym__literal] = "_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_func_repeat1] = "func_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_iter] = anon_sym_iter,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_expr] = sym_expr,
  [sym_binexpr] = sym_binexpr,
  [sym_unaryexpr] = sym_unaryexpr,
  [sym_block] = sym_block,
  [sym_let] = sym_let,
  [sym_if] = sym_if,
  [sym_iter] = sym_iter,
  [sym_func] = sym_func,
  [sym__literal] = sym__literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_func_repeat1] = aux_sym_func_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_unaryexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_iter] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 4,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 2,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 21,
  [24] = 22,
  [25] = 25,
  [26] = 21,
  [27] = 22,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 29,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 28,
  [39] = 39,
  [40] = 33,
  [41] = 37,
  [42] = 36,
  [43] = 43,
  [44] = 30,
  [45] = 35,
  [46] = 32,
  [47] = 39,
  [48] = 43,
  [49] = 33,
  [50] = 34,
  [51] = 29,
  [52] = 39,
  [53] = 37,
  [54] = 36,
  [55] = 43,
  [56] = 30,
  [57] = 28,
  [58] = 32,
  [59] = 35,
  [60] = 4,
  [61] = 2,
  [62] = 3,
  [63] = 63,
  [64] = 63,
  [65] = 63,
  [66] = 15,
  [67] = 17,
  [68] = 6,
  [69] = 10,
  [70] = 12,
  [71] = 5,
  [72] = 19,
  [73] = 16,
  [74] = 18,
  [75] = 20,
  [76] = 13,
  [77] = 20,
  [78] = 10,
  [79] = 18,
  [80] = 19,
  [81] = 5,
  [82] = 16,
  [83] = 13,
  [84] = 9,
  [85] = 15,
  [86] = 86,
  [87] = 86,
  [88] = 88,
  [89] = 89,
  [90] = 89,
  [91] = 91,
  [92] = 91,
  [93] = 89,
  [94] = 91,
  [95] = 95,
  [96] = 95,
  [97] = 97,
  [98] = 97,
  [99] = 99,
  [100] = 99,
  [101] = 97,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 102,
  [108] = 108,
  [109] = 109,
  [110] = 103,
  [111] = 104,
  [112] = 103,
  [113] = 104,
  [114] = 102,
  [115] = 106,
  [116] = 105,
  [117] = 109,
  [118] = 105,
  [119] = 106,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      if (lookahead == '!') ADVANCE(35);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '%') ADVANCE(20);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(9);
      if (lookahead == 'l') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '|') ADVANCE(45);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '%') ADVANCE(20);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == 'o') ADVANCE(10);
      if (lookahead == '{') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(34);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '|') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(38);
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '%') ADVANCE(20);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == 'e') ADVANCE(53);
      if (lookahead == 'i') ADVANCE(52);
      if (lookahead == 'l') ADVANCE(49);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '|') ADVANCE(45);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '!') ADVANCE(4);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '%') ADVANCE(20);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(21);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == '=') ADVANCE(5);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(52);
      if (lookahead == 'l') ADVANCE(49);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '|') ADVANCE(45);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(46);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_let);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_if);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_else);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_iter);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_iter);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(54);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(41);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(39);
      if (lookahead == 't') ADVANCE(50);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(55);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(43);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(51);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(33);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 16},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 16},
  [10] = {.lex_state = 16},
  [11] = {.lex_state = 16},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 16},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 16},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 16},
  [20] = {.lex_state = 16},
  [21] = {.lex_state = 16},
  [22] = {.lex_state = 16},
  [23] = {.lex_state = 16},
  [24] = {.lex_state = 16},
  [25] = {.lex_state = 16},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 16},
  [29] = {.lex_state = 16},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 16},
  [34] = {.lex_state = 16},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 16},
  [37] = {.lex_state = 16},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 16},
  [40] = {.lex_state = 16},
  [41] = {.lex_state = 16},
  [42] = {.lex_state = 16},
  [43] = {.lex_state = 16},
  [44] = {.lex_state = 16},
  [45] = {.lex_state = 16},
  [46] = {.lex_state = 16},
  [47] = {.lex_state = 16},
  [48] = {.lex_state = 16},
  [49] = {.lex_state = 16},
  [50] = {.lex_state = 16},
  [51] = {.lex_state = 16},
  [52] = {.lex_state = 16},
  [53] = {.lex_state = 16},
  [54] = {.lex_state = 16},
  [55] = {.lex_state = 16},
  [56] = {.lex_state = 16},
  [57] = {.lex_state = 16},
  [58] = {.lex_state = 16},
  [59] = {.lex_state = 16},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 16},
  [64] = {.lex_state = 16},
  [65] = {.lex_state = 16},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 16},
  [76] = {.lex_state = 16},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 16},
  [79] = {.lex_state = 16},
  [80] = {.lex_state = 16},
  [81] = {.lex_state = 16},
  [82] = {.lex_state = 16},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 16},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 2},
  [119] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_iter] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(108),
    [sym_expr] = STATE(11),
    [sym_binexpr] = STATE(9),
    [sym_unaryexpr] = STATE(9),
    [sym_block] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [sym_iter] = STATE(9),
    [sym_func] = STATE(9),
    [sym__literal] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [2] = {
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(25),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_else] = ACTIONS(25),
    [anon_sym_iter] = ACTIONS(25),
    [anon_sym_PIPE] = ACTIONS(23),
    [anon_sym_DASH_GT] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
  },
  [3] = {
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_EQ_EQ] = ACTIONS(27),
    [anon_sym_BANG_EQ] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(27),
    [anon_sym_RBRACE] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_else] = ACTIONS(31),
    [anon_sym_iter] = ACTIONS(29),
    [anon_sym_PIPE] = ACTIONS(27),
    [anon_sym_DASH_GT] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [sym_string] = ACTIONS(27),
    [sym_number] = ACTIONS(27),
  },
  [4] = {
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_PERCENT] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_EQ_EQ] = ACTIONS(33),
    [anon_sym_BANG_EQ] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_let] = ACTIONS(35),
    [anon_sym_if] = ACTIONS(35),
    [anon_sym_else] = ACTIONS(35),
    [anon_sym_iter] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(33),
    [anon_sym_DASH_GT] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [sym_string] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
  },
  [5] = {
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_let] = ACTIONS(49),
    [anon_sym_if] = ACTIONS(49),
    [anon_sym_iter] = ACTIONS(49),
    [anon_sym_PIPE] = ACTIONS(37),
    [anon_sym_DASH_GT] = ACTIONS(37),
    [sym_identifier] = ACTIONS(49),
    [sym_string] = ACTIONS(37),
    [sym_number] = ACTIONS(37),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [anon_sym_STAR] = ACTIONS(51),
    [anon_sym_SLASH] = ACTIONS(51),
    [anon_sym_PERCENT] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(51),
    [anon_sym_DASH] = ACTIONS(53),
    [anon_sym_EQ_EQ] = ACTIONS(51),
    [anon_sym_BANG_EQ] = ACTIONS(51),
    [anon_sym_LT] = ACTIONS(53),
    [anon_sym_LT_EQ] = ACTIONS(51),
    [anon_sym_GT] = ACTIONS(53),
    [anon_sym_GT_EQ] = ACTIONS(51),
    [anon_sym_LBRACE] = ACTIONS(51),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_let] = ACTIONS(53),
    [anon_sym_if] = ACTIONS(53),
    [anon_sym_iter] = ACTIONS(53),
    [anon_sym_PIPE] = ACTIONS(51),
    [anon_sym_DASH_GT] = ACTIONS(51),
    [sym_identifier] = ACTIONS(53),
    [sym_string] = ACTIONS(51),
    [sym_number] = ACTIONS(51),
  },
  [7] = {
    [ts_builtin_sym_end] = ACTIONS(33),
    [anon_sym_STAR] = ACTIONS(33),
    [anon_sym_SLASH] = ACTIONS(33),
    [anon_sym_PERCENT] = ACTIONS(33),
    [anon_sym_PLUS] = ACTIONS(33),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_EQ_EQ] = ACTIONS(33),
    [anon_sym_BANG_EQ] = ACTIONS(33),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_LT_EQ] = ACTIONS(33),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_GT_EQ] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(33),
    [anon_sym_let] = ACTIONS(35),
    [anon_sym_if] = ACTIONS(35),
    [anon_sym_iter] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(33),
    [anon_sym_DASH_GT] = ACTIONS(33),
    [sym_identifier] = ACTIONS(35),
    [sym_string] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
  },
  [8] = {
    [sym_expr] = STATE(11),
    [sym_binexpr] = STATE(9),
    [sym_unaryexpr] = STATE(9),
    [sym_block] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [sym_iter] = STATE(9),
    [sym_func] = STATE(9),
    [sym__literal] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(55),
    [anon_sym_DASH] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_let] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(66),
    [anon_sym_iter] = ACTIONS(69),
    [anon_sym_PIPE] = ACTIONS(72),
    [anon_sym_DASH_GT] = ACTIONS(75),
    [sym_identifier] = ACTIONS(78),
    [sym_string] = ACTIONS(81),
    [sym_number] = ACTIONS(81),
  },
  [9] = {
    [ts_builtin_sym_end] = ACTIONS(84),
    [anon_sym_STAR] = ACTIONS(84),
    [anon_sym_SLASH] = ACTIONS(84),
    [anon_sym_PERCENT] = ACTIONS(84),
    [anon_sym_PLUS] = ACTIONS(84),
    [anon_sym_DASH] = ACTIONS(86),
    [anon_sym_EQ_EQ] = ACTIONS(84),
    [anon_sym_BANG_EQ] = ACTIONS(84),
    [anon_sym_LT] = ACTIONS(86),
    [anon_sym_LT_EQ] = ACTIONS(84),
    [anon_sym_GT] = ACTIONS(86),
    [anon_sym_GT_EQ] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(84),
    [anon_sym_RBRACE] = ACTIONS(84),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(86),
    [anon_sym_iter] = ACTIONS(86),
    [anon_sym_PIPE] = ACTIONS(84),
    [anon_sym_DASH_GT] = ACTIONS(84),
    [sym_identifier] = ACTIONS(86),
    [sym_string] = ACTIONS(84),
    [sym_number] = ACTIONS(84),
  },
  [10] = {
    [ts_builtin_sym_end] = ACTIONS(88),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(88),
    [anon_sym_RBRACE] = ACTIONS(88),
    [anon_sym_let] = ACTIONS(90),
    [anon_sym_if] = ACTIONS(90),
    [anon_sym_iter] = ACTIONS(90),
    [anon_sym_PIPE] = ACTIONS(88),
    [anon_sym_DASH_GT] = ACTIONS(88),
    [sym_identifier] = ACTIONS(90),
    [sym_string] = ACTIONS(88),
    [sym_number] = ACTIONS(88),
  },
  [11] = {
    [ts_builtin_sym_end] = ACTIONS(92),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(92),
    [anon_sym_RBRACE] = ACTIONS(92),
    [anon_sym_let] = ACTIONS(94),
    [anon_sym_if] = ACTIONS(94),
    [anon_sym_iter] = ACTIONS(94),
    [anon_sym_PIPE] = ACTIONS(92),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(94),
    [sym_string] = ACTIONS(92),
    [sym_number] = ACTIONS(92),
  },
  [12] = {
    [ts_builtin_sym_end] = ACTIONS(96),
    [anon_sym_STAR] = ACTIONS(96),
    [anon_sym_SLASH] = ACTIONS(96),
    [anon_sym_PERCENT] = ACTIONS(96),
    [anon_sym_PLUS] = ACTIONS(96),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_EQ_EQ] = ACTIONS(96),
    [anon_sym_BANG_EQ] = ACTIONS(96),
    [anon_sym_LT] = ACTIONS(98),
    [anon_sym_LT_EQ] = ACTIONS(96),
    [anon_sym_GT] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_LBRACE] = ACTIONS(96),
    [anon_sym_RBRACE] = ACTIONS(96),
    [anon_sym_let] = ACTIONS(98),
    [anon_sym_if] = ACTIONS(98),
    [anon_sym_iter] = ACTIONS(98),
    [anon_sym_PIPE] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [sym_identifier] = ACTIONS(98),
    [sym_string] = ACTIONS(96),
    [sym_number] = ACTIONS(96),
  },
  [13] = {
    [ts_builtin_sym_end] = ACTIONS(100),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(100),
    [anon_sym_RBRACE] = ACTIONS(100),
    [anon_sym_let] = ACTIONS(102),
    [anon_sym_if] = ACTIONS(102),
    [anon_sym_iter] = ACTIONS(102),
    [anon_sym_PIPE] = ACTIONS(100),
    [anon_sym_DASH_GT] = ACTIONS(100),
    [sym_identifier] = ACTIONS(102),
    [sym_string] = ACTIONS(100),
    [sym_number] = ACTIONS(100),
  },
  [14] = {
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(25),
    [anon_sym_if] = ACTIONS(25),
    [anon_sym_iter] = ACTIONS(25),
    [anon_sym_PIPE] = ACTIONS(23),
    [anon_sym_DASH_GT] = ACTIONS(23),
    [sym_identifier] = ACTIONS(25),
    [sym_string] = ACTIONS(23),
    [sym_number] = ACTIONS(23),
  },
  [15] = {
    [ts_builtin_sym_end] = ACTIONS(96),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(96),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_EQ_EQ] = ACTIONS(96),
    [anon_sym_BANG_EQ] = ACTIONS(96),
    [anon_sym_LT] = ACTIONS(98),
    [anon_sym_LT_EQ] = ACTIONS(96),
    [anon_sym_GT] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_LBRACE] = ACTIONS(96),
    [anon_sym_RBRACE] = ACTIONS(96),
    [anon_sym_let] = ACTIONS(98),
    [anon_sym_if] = ACTIONS(98),
    [anon_sym_iter] = ACTIONS(98),
    [anon_sym_PIPE] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [sym_identifier] = ACTIONS(98),
    [sym_string] = ACTIONS(96),
    [sym_number] = ACTIONS(96),
  },
  [16] = {
    [ts_builtin_sym_end] = ACTIONS(96),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(96),
    [anon_sym_BANG_EQ] = ACTIONS(96),
    [anon_sym_LT] = ACTIONS(98),
    [anon_sym_LT_EQ] = ACTIONS(96),
    [anon_sym_GT] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_LBRACE] = ACTIONS(96),
    [anon_sym_RBRACE] = ACTIONS(96),
    [anon_sym_let] = ACTIONS(98),
    [anon_sym_if] = ACTIONS(98),
    [anon_sym_iter] = ACTIONS(98),
    [anon_sym_PIPE] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [sym_identifier] = ACTIONS(98),
    [sym_string] = ACTIONS(96),
    [sym_number] = ACTIONS(96),
  },
  [17] = {
    [ts_builtin_sym_end] = ACTIONS(104),
    [anon_sym_STAR] = ACTIONS(104),
    [anon_sym_SLASH] = ACTIONS(104),
    [anon_sym_PERCENT] = ACTIONS(104),
    [anon_sym_PLUS] = ACTIONS(104),
    [anon_sym_DASH] = ACTIONS(106),
    [anon_sym_EQ_EQ] = ACTIONS(104),
    [anon_sym_BANG_EQ] = ACTIONS(104),
    [anon_sym_LT] = ACTIONS(106),
    [anon_sym_LT_EQ] = ACTIONS(104),
    [anon_sym_GT] = ACTIONS(106),
    [anon_sym_GT_EQ] = ACTIONS(104),
    [anon_sym_LBRACE] = ACTIONS(104),
    [anon_sym_RBRACE] = ACTIONS(104),
    [anon_sym_let] = ACTIONS(106),
    [anon_sym_if] = ACTIONS(106),
    [anon_sym_iter] = ACTIONS(106),
    [anon_sym_PIPE] = ACTIONS(104),
    [anon_sym_DASH_GT] = ACTIONS(104),
    [sym_identifier] = ACTIONS(106),
    [sym_string] = ACTIONS(104),
    [sym_number] = ACTIONS(104),
  },
  [18] = {
    [ts_builtin_sym_end] = ACTIONS(108),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(108),
    [anon_sym_let] = ACTIONS(110),
    [anon_sym_if] = ACTIONS(110),
    [anon_sym_iter] = ACTIONS(110),
    [anon_sym_PIPE] = ACTIONS(108),
    [anon_sym_DASH_GT] = ACTIONS(108),
    [sym_identifier] = ACTIONS(110),
    [sym_string] = ACTIONS(108),
    [sym_number] = ACTIONS(108),
  },
  [19] = {
    [ts_builtin_sym_end] = ACTIONS(112),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(112),
    [anon_sym_RBRACE] = ACTIONS(112),
    [anon_sym_let] = ACTIONS(114),
    [anon_sym_if] = ACTIONS(114),
    [anon_sym_iter] = ACTIONS(114),
    [anon_sym_PIPE] = ACTIONS(112),
    [anon_sym_DASH_GT] = ACTIONS(112),
    [sym_identifier] = ACTIONS(114),
    [sym_string] = ACTIONS(112),
    [sym_number] = ACTIONS(112),
  },
  [20] = {
    [ts_builtin_sym_end] = ACTIONS(116),
    [anon_sym_STAR] = ACTIONS(39),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(39),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(116),
    [anon_sym_RBRACE] = ACTIONS(116),
    [anon_sym_let] = ACTIONS(118),
    [anon_sym_if] = ACTIONS(118),
    [anon_sym_iter] = ACTIONS(118),
    [anon_sym_PIPE] = ACTIONS(116),
    [anon_sym_DASH_GT] = ACTIONS(116),
    [sym_identifier] = ACTIONS(118),
    [sym_string] = ACTIONS(116),
    [sym_number] = ACTIONS(116),
  },
  [21] = {
    [sym_expr] = STATE(11),
    [sym_binexpr] = STATE(9),
    [sym_unaryexpr] = STATE(9),
    [sym_block] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [sym_iter] = STATE(9),
    [sym_func] = STATE(9),
    [sym__literal] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(27),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(120),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [22] = {
    [sym_expr] = STATE(11),
    [sym_binexpr] = STATE(9),
    [sym_unaryexpr] = STATE(9),
    [sym_block] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [sym_iter] = STATE(9),
    [sym_func] = STATE(9),
    [sym__literal] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(122),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [23] = {
    [sym_expr] = STATE(11),
    [sym_binexpr] = STATE(9),
    [sym_unaryexpr] = STATE(9),
    [sym_block] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [sym_iter] = STATE(9),
    [sym_func] = STATE(9),
    [sym__literal] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(24),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(124),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [24] = {
    [sym_expr] = STATE(11),
    [sym_binexpr] = STATE(9),
    [sym_unaryexpr] = STATE(9),
    [sym_block] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [sym_iter] = STATE(9),
    [sym_func] = STATE(9),
    [sym__literal] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(126),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [25] = {
    [sym_expr] = STATE(11),
    [sym_binexpr] = STATE(9),
    [sym_unaryexpr] = STATE(9),
    [sym_block] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [sym_iter] = STATE(9),
    [sym_func] = STATE(9),
    [sym__literal] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(128),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [26] = {
    [sym_expr] = STATE(11),
    [sym_binexpr] = STATE(9),
    [sym_unaryexpr] = STATE(9),
    [sym_block] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [sym_iter] = STATE(9),
    [sym_func] = STATE(9),
    [sym__literal] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(22),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(130),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [27] = {
    [sym_expr] = STATE(11),
    [sym_binexpr] = STATE(9),
    [sym_unaryexpr] = STATE(9),
    [sym_block] = STATE(9),
    [sym_let] = STATE(9),
    [sym_if] = STATE(9),
    [sym_iter] = STATE(9),
    [sym_func] = STATE(9),
    [sym__literal] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(8),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(132),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(79), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [42] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(77), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [84] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(5), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [126] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(75), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [168] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(19), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [210] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(65), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [252] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(87), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [294] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(13), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [336] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(16), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [378] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(15), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [420] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(18), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [462] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(12), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [504] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(63), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [546] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(85), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [588] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(82), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [630] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(10), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [672] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(81), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [714] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(83), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [756] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(80), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [798] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(12), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [840] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(78), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [882] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(64), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [924] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(86), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [966] = 11,
    ACTIONS(5), 1,
      anon_sym_DASH,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(17), 1,
      anon_sym_DASH_GT,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(20), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [1008] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(70), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [1050] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(66), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [1092] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(73), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [1134] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(69), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [1176] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(71), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [1218] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(74), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [1260] = 11,
    ACTIONS(144), 1,
      anon_sym_DASH,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(148), 1,
      anon_sym_let,
    ACTIONS(150), 1,
      anon_sym_if,
    ACTIONS(152), 1,
      anon_sym_iter,
    ACTIONS(154), 1,
      anon_sym_PIPE,
    ACTIONS(156), 1,
      anon_sym_DASH_GT,
    ACTIONS(158), 1,
      sym_identifier,
    STATE(72), 1,
      sym_expr,
    ACTIONS(160), 2,
      sym_string,
      sym_number,
    STATE(84), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [1302] = 11,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_iter,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_DASH,
    ACTIONS(136), 1,
      anon_sym_let,
    ACTIONS(138), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_PIPE,
    ACTIONS(142), 1,
      anon_sym_DASH_GT,
    STATE(76), 1,
      sym_expr,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    STATE(9), 8,
      sym_binexpr,
      sym_unaryexpr,
      sym_block,
      sym_let,
      sym_if,
      sym_iter,
      sym_func,
      sym__literal,
  [1344] = 2,
    ACTIONS(35), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 12,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_else,
      anon_sym_of,
  [1363] = 2,
    ACTIONS(25), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(23), 12,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
      anon_sym_else,
      anon_sym_of,
  [1382] = 3,
    ACTIONS(162), 1,
      anon_sym_else,
    ACTIONS(29), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(27), 10,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_of,
  [1402] = 6,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    STATE(62), 1,
      sym_block,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(168), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1428] = 6,
    ACTIONS(172), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_block,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(168), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1454] = 6,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    STATE(3), 1,
      sym_block,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(168), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1480] = 3,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(96), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_of,
  [1499] = 2,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 10,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_of,
  [1516] = 2,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 10,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_of,
  [1533] = 5,
    ACTIONS(88), 1,
      anon_sym_of,
    ACTIONS(176), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(178), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1556] = 2,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(96), 10,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_of,
  [1573] = 5,
    ACTIONS(37), 1,
      anon_sym_of,
    ACTIONS(176), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(178), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1596] = 5,
    ACTIONS(112), 1,
      anon_sym_of,
    ACTIONS(176), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(178), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1619] = 4,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(176), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(96), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_of,
  [1640] = 5,
    ACTIONS(108), 1,
      anon_sym_of,
    ACTIONS(176), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(178), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1663] = 5,
    ACTIONS(116), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(168), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1686] = 5,
    ACTIONS(100), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(168), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1709] = 5,
    ACTIONS(116), 1,
      anon_sym_of,
    ACTIONS(176), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(178), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1732] = 5,
    ACTIONS(88), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(168), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1755] = 5,
    ACTIONS(108), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(168), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1778] = 5,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(168), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1801] = 5,
    ACTIONS(37), 1,
      anon_sym_LBRACE,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(170), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(168), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1824] = 4,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(166), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(96), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
  [1845] = 5,
    ACTIONS(100), 1,
      anon_sym_of,
    ACTIONS(176), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(178), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1868] = 2,
    ACTIONS(86), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(84), 10,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_of,
  [1885] = 3,
    ACTIONS(98), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(96), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_LBRACE,
  [1904] = 5,
    ACTIONS(182), 1,
      anon_sym_of,
    ACTIONS(176), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(178), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1927] = 5,
    ACTIONS(184), 1,
      anon_sym_of,
    ACTIONS(176), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(180), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(174), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(178), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1950] = 3,
    ACTIONS(186), 1,
      anon_sym_PIPE,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(88), 1,
      aux_sym_func_repeat1,
  [1960] = 3,
    ACTIONS(191), 1,
      anon_sym_PIPE,
    ACTIONS(193), 1,
      sym_identifier,
    STATE(88), 1,
      aux_sym_func_repeat1,
  [1970] = 3,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(195), 1,
      anon_sym_PIPE,
    STATE(88), 1,
      aux_sym_func_repeat1,
  [1980] = 3,
    ACTIONS(197), 1,
      anon_sym_PIPE,
    ACTIONS(199), 1,
      sym_identifier,
    STATE(90), 1,
      aux_sym_func_repeat1,
  [1990] = 3,
    ACTIONS(201), 1,
      anon_sym_PIPE,
    ACTIONS(203), 1,
      sym_identifier,
    STATE(93), 1,
      aux_sym_func_repeat1,
  [2000] = 3,
    ACTIONS(193), 1,
      sym_identifier,
    ACTIONS(205), 1,
      anon_sym_PIPE,
    STATE(88), 1,
      aux_sym_func_repeat1,
  [2010] = 3,
    ACTIONS(207), 1,
      anon_sym_PIPE,
    ACTIONS(209), 1,
      sym_identifier,
    STATE(89), 1,
      aux_sym_func_repeat1,
  [2020] = 2,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_block,
  [2027] = 2,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_block,
  [2034] = 2,
    ACTIONS(211), 1,
      anon_sym_BANG,
    ACTIONS(213), 1,
      sym_identifier,
  [2041] = 2,
    ACTIONS(215), 1,
      anon_sym_BANG,
    ACTIONS(217), 1,
      sym_identifier,
  [2048] = 2,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    STATE(68), 1,
      sym_block,
  [2055] = 2,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(6), 1,
      sym_block,
  [2062] = 2,
    ACTIONS(219), 1,
      anon_sym_BANG,
    ACTIONS(221), 1,
      sym_identifier,
  [2069] = 1,
    ACTIONS(223), 1,
      anon_sym_EQ,
  [2073] = 1,
    ACTIONS(225), 1,
      anon_sym_DASH_GT,
  [2077] = 1,
    ACTIONS(227), 1,
      anon_sym_EQ,
  [2081] = 1,
    ACTIONS(229), 1,
      sym_identifier,
  [2085] = 1,
    ACTIONS(231), 1,
      anon_sym_DASH_GT,
  [2089] = 1,
    ACTIONS(233), 1,
      anon_sym_EQ,
  [2093] = 1,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [2097] = 1,
    ACTIONS(237), 1,
      sym_identifier,
  [2101] = 1,
    ACTIONS(239), 1,
      anon_sym_DASH_GT,
  [2105] = 1,
    ACTIONS(241), 1,
      anon_sym_EQ,
  [2109] = 1,
    ACTIONS(243), 1,
      anon_sym_DASH_GT,
  [2113] = 1,
    ACTIONS(245), 1,
      anon_sym_EQ,
  [2117] = 1,
    ACTIONS(247), 1,
      anon_sym_EQ,
  [2121] = 1,
    ACTIONS(249), 1,
      anon_sym_DASH_GT,
  [2125] = 1,
    ACTIONS(251), 1,
      sym_identifier,
  [2129] = 1,
    ACTIONS(253), 1,
      sym_identifier,
  [2133] = 1,
    ACTIONS(255), 1,
      sym_identifier,
  [2137] = 1,
    ACTIONS(257), 1,
      anon_sym_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(28)] = 0,
  [SMALL_STATE(29)] = 42,
  [SMALL_STATE(30)] = 84,
  [SMALL_STATE(31)] = 126,
  [SMALL_STATE(32)] = 168,
  [SMALL_STATE(33)] = 210,
  [SMALL_STATE(34)] = 252,
  [SMALL_STATE(35)] = 294,
  [SMALL_STATE(36)] = 336,
  [SMALL_STATE(37)] = 378,
  [SMALL_STATE(38)] = 420,
  [SMALL_STATE(39)] = 462,
  [SMALL_STATE(40)] = 504,
  [SMALL_STATE(41)] = 546,
  [SMALL_STATE(42)] = 588,
  [SMALL_STATE(43)] = 630,
  [SMALL_STATE(44)] = 672,
  [SMALL_STATE(45)] = 714,
  [SMALL_STATE(46)] = 756,
  [SMALL_STATE(47)] = 798,
  [SMALL_STATE(48)] = 840,
  [SMALL_STATE(49)] = 882,
  [SMALL_STATE(50)] = 924,
  [SMALL_STATE(51)] = 966,
  [SMALL_STATE(52)] = 1008,
  [SMALL_STATE(53)] = 1050,
  [SMALL_STATE(54)] = 1092,
  [SMALL_STATE(55)] = 1134,
  [SMALL_STATE(56)] = 1176,
  [SMALL_STATE(57)] = 1218,
  [SMALL_STATE(58)] = 1260,
  [SMALL_STATE(59)] = 1302,
  [SMALL_STATE(60)] = 1344,
  [SMALL_STATE(61)] = 1363,
  [SMALL_STATE(62)] = 1382,
  [SMALL_STATE(63)] = 1402,
  [SMALL_STATE(64)] = 1428,
  [SMALL_STATE(65)] = 1454,
  [SMALL_STATE(66)] = 1480,
  [SMALL_STATE(67)] = 1499,
  [SMALL_STATE(68)] = 1516,
  [SMALL_STATE(69)] = 1533,
  [SMALL_STATE(70)] = 1556,
  [SMALL_STATE(71)] = 1573,
  [SMALL_STATE(72)] = 1596,
  [SMALL_STATE(73)] = 1619,
  [SMALL_STATE(74)] = 1640,
  [SMALL_STATE(75)] = 1663,
  [SMALL_STATE(76)] = 1686,
  [SMALL_STATE(77)] = 1709,
  [SMALL_STATE(78)] = 1732,
  [SMALL_STATE(79)] = 1755,
  [SMALL_STATE(80)] = 1778,
  [SMALL_STATE(81)] = 1801,
  [SMALL_STATE(82)] = 1824,
  [SMALL_STATE(83)] = 1845,
  [SMALL_STATE(84)] = 1868,
  [SMALL_STATE(85)] = 1885,
  [SMALL_STATE(86)] = 1904,
  [SMALL_STATE(87)] = 1927,
  [SMALL_STATE(88)] = 1950,
  [SMALL_STATE(89)] = 1960,
  [SMALL_STATE(90)] = 1970,
  [SMALL_STATE(91)] = 1980,
  [SMALL_STATE(92)] = 1990,
  [SMALL_STATE(93)] = 2000,
  [SMALL_STATE(94)] = 2010,
  [SMALL_STATE(95)] = 2020,
  [SMALL_STATE(96)] = 2027,
  [SMALL_STATE(97)] = 2034,
  [SMALL_STATE(98)] = 2041,
  [SMALL_STATE(99)] = 2048,
  [SMALL_STATE(100)] = 2055,
  [SMALL_STATE(101)] = 2062,
  [SMALL_STATE(102)] = 2069,
  [SMALL_STATE(103)] = 2073,
  [SMALL_STATE(104)] = 2077,
  [SMALL_STATE(105)] = 2081,
  [SMALL_STATE(106)] = 2085,
  [SMALL_STATE(107)] = 2089,
  [SMALL_STATE(108)] = 2093,
  [SMALL_STATE(109)] = 2097,
  [SMALL_STATE(110)] = 2101,
  [SMALL_STATE(111)] = 2105,
  [SMALL_STATE(112)] = 2109,
  [SMALL_STATE(113)] = 2113,
  [SMALL_STATE(114)] = 2117,
  [SMALL_STATE(115)] = 2121,
  [SMALL_STATE(116)] = 2125,
  [SMALL_STATE(117)] = 2129,
  [SMALL_STATE(118)] = 2133,
  [SMALL_STATE(119)] = 2137,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 3),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 3),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 4),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 4),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iter, 5),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_iter, 5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(35),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(23),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(97),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(49),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(50),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(92),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(9),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(9),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 5),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 5),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binexpr, 3),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binexpr, 3),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unaryexpr, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unaryexpr, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 5),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 5),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 5),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 5),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 4),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 4),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 2),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2), SHIFT_REPEAT(88),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_dyn(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
