#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 33
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_PLUS = 1,
  anon_sym_STAR = 2,
  anon_sym_DASH = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_if = 6,
  anon_sym_else = 7,
  anon_sym_iter = 8,
  anon_sym_of = 9,
  anon_sym_PIPE = 10,
  anon_sym_DASH_GT = 11,
  anon_sym_LBRACK = 12,
  anon_sym_RBRACK = 13,
  sym_identifier = 14,
  sym_string = 15,
  sym_number = 16,
  sym_source_file = 17,
  sym_expr = 18,
  sym_binexpr = 19,
  sym_unaryexpr = 20,
  sym_block = 21,
  sym_if = 22,
  sym_iter = 23,
  sym_func = 24,
  sym__literal = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_func_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_DASH] = "-",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_iter] = "iter",
  [anon_sym_of] = "of",
  [anon_sym_PIPE] = "|",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_expr] = "expr",
  [sym_binexpr] = "binexpr",
  [sym_unaryexpr] = "unaryexpr",
  [sym_block] = "block",
  [sym_if] = "if",
  [sym_iter] = "iter",
  [sym_func] = "func",
  [sym__literal] = "_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_func_repeat1] = "func_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_iter] = anon_sym_iter,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_expr] = sym_expr,
  [sym_binexpr] = sym_binexpr,
  [sym_unaryexpr] = sym_unaryexpr,
  [sym_block] = sym_block,
  [sym_if] = sym_if,
  [sym_iter] = sym_iter,
  [sym_func] = sym_func,
  [sym__literal] = sym__literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_func_repeat1] = aux_sym_func_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_unaryexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_iter] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 5,
  [7] = 3,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 10,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 19,
  [22] = 17,
  [23] = 17,
  [24] = 15,
  [25] = 18,
  [26] = 13,
  [27] = 13,
  [28] = 14,
  [29] = 10,
  [30] = 18,
  [31] = 14,
  [32] = 15,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 33,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 34,
  [47] = 47,
  [48] = 33,
  [49] = 34,
  [50] = 50,
  [51] = 35,
  [52] = 50,
  [53] = 50,
  [54] = 45,
  [55] = 39,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 36,
  [60] = 58,
  [61] = 44,
  [62] = 41,
  [63] = 39,
  [64] = 41,
  [65] = 47,
  [66] = 43,
  [67] = 38,
  [68] = 58,
  [69] = 44,
  [70] = 56,
  [71] = 45,
  [72] = 56,
  [73] = 73,
  [74] = 73,
  [75] = 37,
  [76] = 47,
  [77] = 77,
  [78] = 77,
  [79] = 79,
  [80] = 79,
  [81] = 81,
  [82] = 82,
  [83] = 82,
  [84] = 84,
  [85] = 81,
  [86] = 86,
  [87] = 86,
  [88] = 81,
  [89] = 86,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '+') ADVANCE(13);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '[') ADVANCE(27);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == 'e') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'o') ADVANCE(5);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(36);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 't') ADVANCE(2);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(3);
      END_STATE();
    case 9:
      if (lookahead == '|') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 10:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '+') ADVANCE(13);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 'i') ADVANCE(31);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '+') ADVANCE(13);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == 'i') ADVANCE(31);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '|') ADVANCE(25);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_if);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_else);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_iter);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_iter);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(21);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(19);
      if (lookahead == 't') ADVANCE(29);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(34);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(23);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(30);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 10},
  [34] = {.lex_state = 10},
  [35] = {.lex_state = 10},
  [36] = {.lex_state = 11},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 11},
  [39] = {.lex_state = 11},
  [40] = {.lex_state = 11},
  [41] = {.lex_state = 11},
  [42] = {.lex_state = 11},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 9},
  [57] = {.lex_state = 9},
  [58] = {.lex_state = 9},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 9},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 9},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 9},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 9},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 9},
  [83] = {.lex_state = 9},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_iter] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(84),
    [sym_expr] = STATE(40),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [2] = {
    [sym_expr] = STATE(40),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(26),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(29),
    [anon_sym_iter] = ACTIONS(32),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_DASH_GT] = ACTIONS(38),
    [sym_identifier] = ACTIONS(41),
    [sym_string] = ACTIONS(44),
    [sym_number] = ACTIONS(44),
  },
  [3] = {
    [sym_expr] = STATE(40),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(47),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [4] = {
    [sym_expr] = STATE(40),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(49),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [5] = {
    [sym_expr] = STATE(40),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(51),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [6] = {
    [sym_expr] = STATE(40),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(4),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [7] = {
    [sym_expr] = STATE(40),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(55),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [8] = {
    [sym_expr] = STATE(40),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(7),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [9] = {
    [sym_expr] = STATE(40),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [10] = {
    [sym_expr] = STATE(36),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [11] = {
    [sym_expr] = STATE(74),
    [sym_binexpr] = STATE(66),
    [sym_unaryexpr] = STATE(66),
    [sym_block] = STATE(66),
    [sym_if] = STATE(66),
    [sym_iter] = STATE(66),
    [sym_func] = STATE(66),
    [sym__literal] = STATE(66),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_iter] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [sym_string] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
  },
  [12] = {
    [sym_expr] = STATE(73),
    [sym_binexpr] = STATE(66),
    [sym_unaryexpr] = STATE(66),
    [sym_block] = STATE(66),
    [sym_if] = STATE(66),
    [sym_iter] = STATE(66),
    [sym_func] = STATE(66),
    [sym__literal] = STATE(66),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_iter] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [sym_string] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
  },
  [13] = {
    [sym_expr] = STATE(62),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(83),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [14] = {
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(83),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [15] = {
    [sym_expr] = STATE(71),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(83),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [16] = {
    [sym_expr] = STATE(36),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(83),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [17] = {
    [sym_expr] = STATE(65),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(83),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [18] = {
    [sym_expr] = STATE(61),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(83),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [19] = {
    [sym_expr] = STATE(53),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(83),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [20] = {
    [sym_expr] = STATE(50),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(83),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [21] = {
    [sym_expr] = STATE(52),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(79),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(81),
    [anon_sym_DASH_GT] = ACTIONS(83),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [22] = {
    [sym_expr] = STATE(47),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [23] = {
    [sym_expr] = STATE(76),
    [sym_binexpr] = STATE(66),
    [sym_unaryexpr] = STATE(66),
    [sym_block] = STATE(66),
    [sym_if] = STATE(66),
    [sym_iter] = STATE(66),
    [sym_func] = STATE(66),
    [sym__literal] = STATE(66),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_iter] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [sym_string] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
  },
  [24] = {
    [sym_expr] = STATE(54),
    [sym_binexpr] = STATE(66),
    [sym_unaryexpr] = STATE(66),
    [sym_block] = STATE(66),
    [sym_if] = STATE(66),
    [sym_iter] = STATE(66),
    [sym_func] = STATE(66),
    [sym__literal] = STATE(66),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_iter] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [sym_string] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
  },
  [25] = {
    [sym_expr] = STATE(69),
    [sym_binexpr] = STATE(66),
    [sym_unaryexpr] = STATE(66),
    [sym_block] = STATE(66),
    [sym_if] = STATE(66),
    [sym_iter] = STATE(66),
    [sym_func] = STATE(66),
    [sym__literal] = STATE(66),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_iter] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [sym_string] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
  },
  [26] = {
    [sym_expr] = STATE(41),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [27] = {
    [sym_expr] = STATE(64),
    [sym_binexpr] = STATE(66),
    [sym_unaryexpr] = STATE(66),
    [sym_block] = STATE(66),
    [sym_if] = STATE(66),
    [sym_iter] = STATE(66),
    [sym_func] = STATE(66),
    [sym__literal] = STATE(66),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_iter] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [sym_string] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
  },
  [28] = {
    [sym_expr] = STATE(63),
    [sym_binexpr] = STATE(66),
    [sym_unaryexpr] = STATE(66),
    [sym_block] = STATE(66),
    [sym_if] = STATE(66),
    [sym_iter] = STATE(66),
    [sym_func] = STATE(66),
    [sym__literal] = STATE(66),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_iter] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [sym_string] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
  },
  [29] = {
    [sym_expr] = STATE(59),
    [sym_binexpr] = STATE(66),
    [sym_unaryexpr] = STATE(66),
    [sym_block] = STATE(66),
    [sym_if] = STATE(66),
    [sym_iter] = STATE(66),
    [sym_func] = STATE(66),
    [sym__literal] = STATE(66),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_if] = ACTIONS(65),
    [anon_sym_iter] = ACTIONS(67),
    [anon_sym_PIPE] = ACTIONS(69),
    [anon_sym_DASH_GT] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [sym_string] = ACTIONS(75),
    [sym_number] = ACTIONS(75),
  },
  [30] = {
    [sym_expr] = STATE(44),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [31] = {
    [sym_expr] = STATE(39),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
  [32] = {
    [sym_expr] = STATE(45),
    [sym_binexpr] = STATE(43),
    [sym_unaryexpr] = STATE(43),
    [sym_block] = STATE(43),
    [sym_if] = STATE(43),
    [sym_iter] = STATE(43),
    [sym_func] = STATE(43),
    [sym__literal] = STATE(43),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_if] = ACTIONS(9),
    [anon_sym_iter] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_DASH_GT] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_number] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(87), 5,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_else,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(85), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [19] = 2,
    ACTIONS(91), 5,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_else,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(89), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [38] = 3,
    ACTIONS(97), 1,
      anon_sym_else,
    ACTIONS(95), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(93), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [59] = 2,
    ACTIONS(101), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(99), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [77] = 2,
    ACTIONS(105), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(103), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [95] = 2,
    ACTIONS(109), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(107), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [113] = 4,
    ACTIONS(113), 1,
      anon_sym_PLUS,
    ACTIONS(115), 1,
      anon_sym_STAR,
    ACTIONS(117), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(111), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [135] = 4,
    ACTIONS(113), 1,
      anon_sym_PLUS,
    ACTIONS(115), 1,
      anon_sym_STAR,
    ACTIONS(121), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [157] = 4,
    ACTIONS(113), 1,
      anon_sym_PLUS,
    ACTIONS(115), 1,
      anon_sym_STAR,
    ACTIONS(125), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(123), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [179] = 2,
    ACTIONS(87), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(85), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [197] = 2,
    ACTIONS(129), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(127), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [215] = 4,
    ACTIONS(113), 1,
      anon_sym_PLUS,
    ACTIONS(115), 1,
      anon_sym_STAR,
    ACTIONS(133), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [237] = 4,
    ACTIONS(113), 1,
      anon_sym_PLUS,
    ACTIONS(115), 1,
      anon_sym_STAR,
    ACTIONS(137), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(135), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [259] = 2,
    ACTIONS(91), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(89), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [277] = 3,
    ACTIONS(115), 1,
      anon_sym_STAR,
    ACTIONS(101), 4,
      anon_sym_DASH,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(99), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [297] = 1,
    ACTIONS(85), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_else,
      anon_sym_of,
  [305] = 1,
    ACTIONS(89), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACE,
      anon_sym_else,
      anon_sym_of,
  [313] = 4,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      anon_sym_PLUS,
    ACTIONS(141), 1,
      anon_sym_STAR,
    STATE(51), 1,
      sym_block,
  [326] = 2,
    ACTIONS(143), 1,
      anon_sym_else,
    ACTIONS(93), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_of,
  [335] = 4,
    ACTIONS(139), 1,
      anon_sym_PLUS,
    ACTIONS(141), 1,
      anon_sym_STAR,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(35), 1,
      sym_block,
  [348] = 4,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      anon_sym_PLUS,
    ACTIONS(141), 1,
      anon_sym_STAR,
    STATE(35), 1,
      sym_block,
  [361] = 3,
    ACTIONS(135), 1,
      anon_sym_of,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(149), 1,
      anon_sym_STAR,
  [371] = 3,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      anon_sym_PLUS,
    ACTIONS(141), 1,
      anon_sym_STAR,
  [381] = 3,
    ACTIONS(151), 1,
      anon_sym_PIPE,
    ACTIONS(153), 1,
      sym_identifier,
    STATE(57), 1,
      aux_sym_func_repeat1,
  [391] = 3,
    ACTIONS(155), 1,
      anon_sym_PIPE,
    ACTIONS(157), 1,
      sym_identifier,
    STATE(57), 1,
      aux_sym_func_repeat1,
  [401] = 3,
    ACTIONS(160), 1,
      anon_sym_PIPE,
    ACTIONS(162), 1,
      sym_identifier,
    STATE(56), 1,
      aux_sym_func_repeat1,
  [411] = 1,
    ACTIONS(99), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_of,
  [417] = 3,
    ACTIONS(164), 1,
      anon_sym_PIPE,
    ACTIONS(166), 1,
      sym_identifier,
    STATE(72), 1,
      aux_sym_func_repeat1,
  [427] = 3,
    ACTIONS(131), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      anon_sym_PLUS,
    ACTIONS(141), 1,
      anon_sym_STAR,
  [437] = 3,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      anon_sym_PLUS,
    ACTIONS(141), 1,
      anon_sym_STAR,
  [447] = 3,
    ACTIONS(111), 1,
      anon_sym_of,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(149), 1,
      anon_sym_STAR,
  [457] = 3,
    ACTIONS(123), 1,
      anon_sym_of,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(149), 1,
      anon_sym_STAR,
  [467] = 2,
    ACTIONS(141), 1,
      anon_sym_STAR,
    ACTIONS(99), 2,
      anon_sym_PLUS,
      anon_sym_LBRACE,
  [475] = 1,
    ACTIONS(127), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_of,
  [481] = 1,
    ACTIONS(107), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_of,
  [487] = 3,
    ACTIONS(168), 1,
      anon_sym_PIPE,
    ACTIONS(170), 1,
      sym_identifier,
    STATE(70), 1,
      aux_sym_func_repeat1,
  [497] = 3,
    ACTIONS(131), 1,
      anon_sym_of,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(149), 1,
      anon_sym_STAR,
  [507] = 3,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(172), 1,
      anon_sym_PIPE,
    STATE(57), 1,
      aux_sym_func_repeat1,
  [517] = 3,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      anon_sym_PLUS,
    ACTIONS(141), 1,
      anon_sym_STAR,
  [527] = 3,
    ACTIONS(153), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_PIPE,
    STATE(57), 1,
      aux_sym_func_repeat1,
  [537] = 3,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(149), 1,
      anon_sym_STAR,
    ACTIONS(176), 1,
      anon_sym_of,
  [547] = 3,
    ACTIONS(147), 1,
      anon_sym_PLUS,
    ACTIONS(149), 1,
      anon_sym_STAR,
    ACTIONS(178), 1,
      anon_sym_of,
  [557] = 1,
    ACTIONS(103), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_of,
  [563] = 2,
    ACTIONS(149), 1,
      anon_sym_STAR,
    ACTIONS(99), 2,
      anon_sym_PLUS,
      anon_sym_of,
  [571] = 2,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    STATE(75), 1,
      sym_block,
  [578] = 2,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(37), 1,
      sym_block,
  [585] = 2,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_block,
  [592] = 2,
    ACTIONS(63), 1,
      anon_sym_LBRACE,
    STATE(67), 1,
      sym_block,
  [599] = 1,
    ACTIONS(180), 1,
      anon_sym_DASH_GT,
  [603] = 1,
    ACTIONS(182), 1,
      sym_identifier,
  [607] = 1,
    ACTIONS(184), 1,
      sym_identifier,
  [611] = 1,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
  [615] = 1,
    ACTIONS(188), 1,
      anon_sym_DASH_GT,
  [619] = 1,
    ACTIONS(190), 1,
      anon_sym_DASH_GT,
  [623] = 1,
    ACTIONS(192), 1,
      anon_sym_DASH_GT,
  [627] = 1,
    ACTIONS(194), 1,
      anon_sym_DASH_GT,
  [631] = 1,
    ACTIONS(196), 1,
      anon_sym_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(33)] = 0,
  [SMALL_STATE(34)] = 19,
  [SMALL_STATE(35)] = 38,
  [SMALL_STATE(36)] = 59,
  [SMALL_STATE(37)] = 77,
  [SMALL_STATE(38)] = 95,
  [SMALL_STATE(39)] = 113,
  [SMALL_STATE(40)] = 135,
  [SMALL_STATE(41)] = 157,
  [SMALL_STATE(42)] = 179,
  [SMALL_STATE(43)] = 197,
  [SMALL_STATE(44)] = 215,
  [SMALL_STATE(45)] = 237,
  [SMALL_STATE(46)] = 259,
  [SMALL_STATE(47)] = 277,
  [SMALL_STATE(48)] = 297,
  [SMALL_STATE(49)] = 305,
  [SMALL_STATE(50)] = 313,
  [SMALL_STATE(51)] = 326,
  [SMALL_STATE(52)] = 335,
  [SMALL_STATE(53)] = 348,
  [SMALL_STATE(54)] = 361,
  [SMALL_STATE(55)] = 371,
  [SMALL_STATE(56)] = 381,
  [SMALL_STATE(57)] = 391,
  [SMALL_STATE(58)] = 401,
  [SMALL_STATE(59)] = 411,
  [SMALL_STATE(60)] = 417,
  [SMALL_STATE(61)] = 427,
  [SMALL_STATE(62)] = 437,
  [SMALL_STATE(63)] = 447,
  [SMALL_STATE(64)] = 457,
  [SMALL_STATE(65)] = 467,
  [SMALL_STATE(66)] = 475,
  [SMALL_STATE(67)] = 481,
  [SMALL_STATE(68)] = 487,
  [SMALL_STATE(69)] = 497,
  [SMALL_STATE(70)] = 507,
  [SMALL_STATE(71)] = 517,
  [SMALL_STATE(72)] = 527,
  [SMALL_STATE(73)] = 537,
  [SMALL_STATE(74)] = 547,
  [SMALL_STATE(75)] = 557,
  [SMALL_STATE(76)] = 563,
  [SMALL_STATE(77)] = 571,
  [SMALL_STATE(78)] = 578,
  [SMALL_STATE(79)] = 585,
  [SMALL_STATE(80)] = 592,
  [SMALL_STATE(81)] = 599,
  [SMALL_STATE(82)] = 603,
  [SMALL_STATE(83)] = 607,
  [SMALL_STATE(84)] = 611,
  [SMALL_STATE(85)] = 615,
  [SMALL_STATE(86)] = 619,
  [SMALL_STATE(87)] = 623,
  [SMALL_STATE(88)] = 627,
  [SMALL_STATE(89)] = 631,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(26),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(5),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(11),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(60),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(30),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(43),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(43),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 3),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binexpr, 3),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binexpr, 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 5),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 5),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iter, 5),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_iter, 5),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 5),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 5),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unaryexpr, 2),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unaryexpr, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 2),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 4),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 4),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2), SHIFT_REPEAT(57),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [186] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_dyn(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
