#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 39
#define SYMBOL_COUNT 33
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_PLUS = 1,
  anon_sym_DASH = 2,
  anon_sym_STAR = 3,
  anon_sym_SLASH = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_let = 7,
  anon_sym_BANG = 8,
  anon_sym_EQ = 9,
  anon_sym_if = 10,
  anon_sym_else = 11,
  anon_sym_iter = 12,
  anon_sym_of = 13,
  anon_sym_PIPE = 14,
  anon_sym_DASH_GT = 15,
  anon_sym_LBRACK = 16,
  anon_sym_RBRACK = 17,
  sym_identifier = 18,
  sym_string = 19,
  sym_number = 20,
  sym_source_file = 21,
  sym_expr = 22,
  sym_binexpr = 23,
  sym_unaryexpr = 24,
  sym_block = 25,
  sym_let = 26,
  sym_if = 27,
  sym_iter = 28,
  sym_func = 29,
  sym__literal = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_func_repeat1 = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_let] = "let",
  [anon_sym_BANG] = "!",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_iter] = "iter",
  [anon_sym_of] = "of",
  [anon_sym_PIPE] = "|",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym_expr] = "expr",
  [sym_binexpr] = "binexpr",
  [sym_unaryexpr] = "unaryexpr",
  [sym_block] = "block",
  [sym_let] = "let",
  [sym_if] = "if",
  [sym_iter] = "iter",
  [sym_func] = "func",
  [sym__literal] = "_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_func_repeat1] = "func_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_iter] = anon_sym_iter,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym_expr] = sym_expr,
  [sym_binexpr] = sym_binexpr,
  [sym_unaryexpr] = sym_unaryexpr,
  [sym_block] = sym_block,
  [sym_let] = sym_let,
  [sym_if] = sym_if,
  [sym_iter] = sym_iter,
  [sym_func] = sym_func,
  [sym__literal] = sym__literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_func_repeat1] = aux_sym_func_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_unaryexpr] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_let] = {
    .visible = true,
    .named = true,
  },
  [sym_if] = {
    .visible = true,
    .named = true,
  },
  [sym_iter] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_func_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 4,
  [7] = 3,
  [8] = 4,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 13,
  [17] = 17,
  [18] = 10,
  [19] = 17,
  [20] = 20,
  [21] = 11,
  [22] = 22,
  [23] = 23,
  [24] = 22,
  [25] = 22,
  [26] = 10,
  [27] = 14,
  [28] = 20,
  [29] = 13,
  [30] = 15,
  [31] = 12,
  [32] = 20,
  [33] = 15,
  [34] = 14,
  [35] = 11,
  [36] = 17,
  [37] = 12,
  [38] = 23,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 41,
  [52] = 52,
  [53] = 40,
  [54] = 54,
  [55] = 55,
  [56] = 40,
  [57] = 41,
  [58] = 58,
  [59] = 39,
  [60] = 58,
  [61] = 58,
  [62] = 42,
  [63] = 49,
  [64] = 44,
  [65] = 45,
  [66] = 47,
  [67] = 46,
  [68] = 50,
  [69] = 48,
  [70] = 47,
  [71] = 52,
  [72] = 42,
  [73] = 54,
  [74] = 74,
  [75] = 43,
  [76] = 48,
  [77] = 74,
  [78] = 45,
  [79] = 46,
  [80] = 54,
  [81] = 52,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 82,
  [86] = 84,
  [87] = 82,
  [88] = 84,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 91,
  [93] = 89,
  [94] = 90,
  [95] = 90,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 98,
  [101] = 96,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 98,
  [106] = 97,
  [107] = 103,
  [108] = 96,
  [109] = 104,
  [110] = 99,
  [111] = 104,
  [112] = 99,
  [113] = 97,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == '=') ADVANCE(24);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == 'e') ADVANCE(8);
      if (lookahead == 'i') ADVANCE(6);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '|') ADVANCE(32);
      if (lookahead == '}') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(23);
      if (lookahead == '|') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(45);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == 'f') ADVANCE(25);
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(40);
      if (lookahead == 'i') ADVANCE(39);
      if (lookahead == 'l') ADVANCE(36);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '|') ADVANCE(32);
      if (lookahead == '}') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(39);
      if (lookahead == 'l') ADVANCE(36);
      if (lookahead == '{') ADVANCE(19);
      if (lookahead == '|') ADVANCE(32);
      if (lookahead == '}') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_let);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_if);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_else);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_iter);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_iter);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(43);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(41);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(28);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead == 't') ADVANCE(37);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(42);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(30);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(38);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(22);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 13},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 13},
  [9] = {.lex_state = 13},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 13},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 13},
  [22] = {.lex_state = 13},
  [23] = {.lex_state = 13},
  [24] = {.lex_state = 13},
  [25] = {.lex_state = 13},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 13},
  [28] = {.lex_state = 13},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 13},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 12},
  [41] = {.lex_state = 12},
  [42] = {.lex_state = 13},
  [43] = {.lex_state = 13},
  [44] = {.lex_state = 13},
  [45] = {.lex_state = 13},
  [46] = {.lex_state = 13},
  [47] = {.lex_state = 13},
  [48] = {.lex_state = 13},
  [49] = {.lex_state = 13},
  [50] = {.lex_state = 13},
  [51] = {.lex_state = 13},
  [52] = {.lex_state = 13},
  [53] = {.lex_state = 13},
  [54] = {.lex_state = 13},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_iter] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(102),
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [2] = {
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_let] = ACTIONS(31),
    [anon_sym_if] = ACTIONS(34),
    [anon_sym_iter] = ACTIONS(37),
    [anon_sym_PIPE] = ACTIONS(40),
    [anon_sym_DASH_GT] = ACTIONS(43),
    [sym_identifier] = ACTIONS(46),
    [sym_string] = ACTIONS(49),
    [sym_number] = ACTIONS(49),
  },
  [3] = {
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(52),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [4] = {
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(3),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(54),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [5] = {
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(56),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [6] = {
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(7),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(58),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [7] = {
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(60),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [8] = {
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(5),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_RBRACE] = ACTIONS(62),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [9] = {
    [sym_expr] = STATE(55),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(64),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [10] = {
    [sym_expr] = STATE(46),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [11] = {
    [sym_expr] = STATE(50),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [12] = {
    [sym_expr] = STATE(73),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
  [13] = {
    [sym_expr] = STATE(78),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [14] = {
    [sym_expr] = STATE(71),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
  [15] = {
    [sym_expr] = STATE(61),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [16] = {
    [sym_expr] = STATE(65),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
  [17] = {
    [sym_expr] = STATE(76),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [18] = {
    [sym_expr] = STATE(79),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [19] = {
    [sym_expr] = STATE(69),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
  [20] = {
    [sym_expr] = STATE(70),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [21] = {
    [sym_expr] = STATE(50),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [22] = {
    [sym_expr] = STATE(72),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [23] = {
    [sym_expr] = STATE(77),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
  [24] = {
    [sym_expr] = STATE(42),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [25] = {
    [sym_expr] = STATE(62),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
  [26] = {
    [sym_expr] = STATE(67),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
  [27] = {
    [sym_expr] = STATE(81),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [28] = {
    [sym_expr] = STATE(47),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [29] = {
    [sym_expr] = STATE(45),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [30] = {
    [sym_expr] = STATE(60),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [31] = {
    [sym_expr] = STATE(54),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [32] = {
    [sym_expr] = STATE(66),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
  [33] = {
    [sym_expr] = STATE(58),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [34] = {
    [sym_expr] = STATE(52),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [35] = {
    [sym_expr] = STATE(68),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
  [36] = {
    [sym_expr] = STATE(48),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [37] = {
    [sym_expr] = STATE(80),
    [sym_binexpr] = STATE(49),
    [sym_unaryexpr] = STATE(49),
    [sym_block] = STATE(49),
    [sym_let] = STATE(49),
    [sym_if] = STATE(49),
    [sym_iter] = STATE(49),
    [sym_func] = STATE(49),
    [sym__literal] = STATE(49),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_LBRACE] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(86),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_iter] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(92),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
  },
  [38] = {
    [sym_expr] = STATE(74),
    [sym_binexpr] = STATE(63),
    [sym_unaryexpr] = STATE(63),
    [sym_block] = STATE(63),
    [sym_let] = STATE(63),
    [sym_if] = STATE(63),
    [sym_iter] = STATE(63),
    [sym_func] = STATE(63),
    [sym__literal] = STATE(63),
    [anon_sym_DASH] = ACTIONS(66),
    [anon_sym_LBRACE] = ACTIONS(68),
    [anon_sym_let] = ACTIONS(70),
    [anon_sym_if] = ACTIONS(72),
    [anon_sym_iter] = ACTIONS(74),
    [anon_sym_PIPE] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(78),
    [sym_identifier] = ACTIONS(80),
    [sym_string] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(98), 1,
      anon_sym_else,
    ACTIONS(96), 5,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(94), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [23] = 2,
    ACTIONS(102), 6,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(100), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [44] = 2,
    ACTIONS(106), 6,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(104), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [65] = 3,
    ACTIONS(112), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(110), 5,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(108), 8,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [87] = 2,
    ACTIONS(116), 5,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(114), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [107] = 2,
    ACTIONS(120), 5,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(118), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [127] = 5,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    ACTIONS(126), 1,
      anon_sym_DASH,
    ACTIONS(112), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(128), 4,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(122), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [153] = 5,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    ACTIONS(126), 1,
      anon_sym_DASH,
    ACTIONS(112), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(132), 4,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(130), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [179] = 5,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    ACTIONS(126), 1,
      anon_sym_DASH,
    ACTIONS(112), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(136), 4,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(134), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [205] = 5,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    ACTIONS(126), 1,
      anon_sym_DASH,
    ACTIONS(112), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(140), 4,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(138), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [231] = 2,
    ACTIONS(144), 5,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(142), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [251] = 2,
    ACTIONS(110), 5,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(108), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [271] = 2,
    ACTIONS(106), 5,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(104), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [291] = 5,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    ACTIONS(126), 1,
      anon_sym_DASH,
    ACTIONS(112), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(148), 4,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(146), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [317] = 2,
    ACTIONS(102), 5,
      anon_sym_DASH,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(100), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [337] = 5,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    ACTIONS(126), 1,
      anon_sym_DASH,
    ACTIONS(112), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(152), 4,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(150), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [363] = 5,
    ACTIONS(124), 1,
      anon_sym_PLUS,
    ACTIONS(126), 1,
      anon_sym_DASH,
    ACTIONS(112), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(156), 4,
      anon_sym_let,
      anon_sym_if,
      anon_sym_iter,
      sym_identifier,
    ACTIONS(154), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_DASH_GT,
      sym_string,
      sym_number,
  [389] = 1,
    ACTIONS(100), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_else,
      anon_sym_of,
  [399] = 1,
    ACTIONS(104), 7,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_LBRACE,
      anon_sym_else,
      anon_sym_of,
  [409] = 4,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_block,
    ACTIONS(158), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [424] = 2,
    ACTIONS(162), 1,
      anon_sym_else,
    ACTIONS(94), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_of,
  [435] = 4,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
    ACTIONS(158), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [450] = 4,
    ACTIONS(164), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_block,
    ACTIONS(158), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [465] = 2,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_of,
  [475] = 1,
    ACTIONS(142), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_of,
  [483] = 1,
    ACTIONS(118), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_of,
  [491] = 3,
    ACTIONS(122), 1,
      anon_sym_of,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [503] = 3,
    ACTIONS(134), 1,
      anon_sym_of,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [515] = 3,
    ACTIONS(130), 1,
      anon_sym_of,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [527] = 1,
    ACTIONS(108), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_of,
  [535] = 3,
    ACTIONS(138), 1,
      anon_sym_of,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [547] = 3,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [559] = 3,
    ACTIONS(146), 1,
      anon_sym_of,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [571] = 2,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(108), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LBRACE,
  [581] = 3,
    ACTIONS(150), 1,
      anon_sym_of,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [593] = 3,
    ACTIONS(170), 1,
      anon_sym_of,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [605] = 1,
    ACTIONS(114), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_of,
  [613] = 3,
    ACTIONS(138), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [625] = 3,
    ACTIONS(172), 1,
      anon_sym_of,
    ACTIONS(166), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(168), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [637] = 3,
    ACTIONS(122), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [649] = 3,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [661] = 3,
    ACTIONS(150), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [673] = 3,
    ACTIONS(146), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(160), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
  [685] = 3,
    ACTIONS(174), 1,
      anon_sym_PIPE,
    ACTIONS(176), 1,
      sym_identifier,
    STATE(84), 1,
      aux_sym_func_repeat1,
  [695] = 3,
    ACTIONS(178), 1,
      anon_sym_PIPE,
    ACTIONS(180), 1,
      sym_identifier,
    STATE(83), 1,
      aux_sym_func_repeat1,
  [705] = 3,
    ACTIONS(183), 1,
      anon_sym_PIPE,
    ACTIONS(185), 1,
      sym_identifier,
    STATE(83), 1,
      aux_sym_func_repeat1,
  [715] = 3,
    ACTIONS(187), 1,
      anon_sym_PIPE,
    ACTIONS(189), 1,
      sym_identifier,
    STATE(86), 1,
      aux_sym_func_repeat1,
  [725] = 3,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(191), 1,
      anon_sym_PIPE,
    STATE(83), 1,
      aux_sym_func_repeat1,
  [735] = 3,
    ACTIONS(193), 1,
      anon_sym_PIPE,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(88), 1,
      aux_sym_func_repeat1,
  [745] = 3,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(197), 1,
      anon_sym_PIPE,
    STATE(83), 1,
      aux_sym_func_repeat1,
  [755] = 2,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_block,
  [762] = 2,
    ACTIONS(199), 1,
      anon_sym_BANG,
    ACTIONS(201), 1,
      sym_identifier,
  [769] = 2,
    ACTIONS(7), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_block,
  [776] = 2,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    STATE(64), 1,
      sym_block,
  [783] = 2,
    ACTIONS(68), 1,
      anon_sym_LBRACE,
    STATE(75), 1,
      sym_block,
  [790] = 2,
    ACTIONS(203), 1,
      anon_sym_BANG,
    ACTIONS(205), 1,
      sym_identifier,
  [797] = 2,
    ACTIONS(207), 1,
      anon_sym_BANG,
    ACTIONS(209), 1,
      sym_identifier,
  [804] = 1,
    ACTIONS(211), 1,
      anon_sym_EQ,
  [808] = 1,
    ACTIONS(213), 1,
      anon_sym_DASH_GT,
  [812] = 1,
    ACTIONS(215), 1,
      anon_sym_EQ,
  [816] = 1,
    ACTIONS(217), 1,
      sym_identifier,
  [820] = 1,
    ACTIONS(219), 1,
      anon_sym_EQ,
  [824] = 1,
    ACTIONS(221), 1,
      anon_sym_EQ,
  [828] = 1,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
  [832] = 1,
    ACTIONS(225), 1,
      sym_identifier,
  [836] = 1,
    ACTIONS(227), 1,
      anon_sym_DASH_GT,
  [840] = 1,
    ACTIONS(229), 1,
      anon_sym_EQ,
  [844] = 1,
    ACTIONS(231), 1,
      anon_sym_DASH_GT,
  [848] = 1,
    ACTIONS(233), 1,
      sym_identifier,
  [852] = 1,
    ACTIONS(235), 1,
      anon_sym_EQ,
  [856] = 1,
    ACTIONS(237), 1,
      anon_sym_DASH_GT,
  [860] = 1,
    ACTIONS(239), 1,
      sym_identifier,
  [864] = 1,
    ACTIONS(241), 1,
      anon_sym_DASH_GT,
  [868] = 1,
    ACTIONS(243), 1,
      sym_identifier,
  [872] = 1,
    ACTIONS(245), 1,
      anon_sym_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(39)] = 0,
  [SMALL_STATE(40)] = 23,
  [SMALL_STATE(41)] = 44,
  [SMALL_STATE(42)] = 65,
  [SMALL_STATE(43)] = 87,
  [SMALL_STATE(44)] = 107,
  [SMALL_STATE(45)] = 127,
  [SMALL_STATE(46)] = 153,
  [SMALL_STATE(47)] = 179,
  [SMALL_STATE(48)] = 205,
  [SMALL_STATE(49)] = 231,
  [SMALL_STATE(50)] = 251,
  [SMALL_STATE(51)] = 271,
  [SMALL_STATE(52)] = 291,
  [SMALL_STATE(53)] = 317,
  [SMALL_STATE(54)] = 337,
  [SMALL_STATE(55)] = 363,
  [SMALL_STATE(56)] = 389,
  [SMALL_STATE(57)] = 399,
  [SMALL_STATE(58)] = 409,
  [SMALL_STATE(59)] = 424,
  [SMALL_STATE(60)] = 435,
  [SMALL_STATE(61)] = 450,
  [SMALL_STATE(62)] = 465,
  [SMALL_STATE(63)] = 475,
  [SMALL_STATE(64)] = 483,
  [SMALL_STATE(65)] = 491,
  [SMALL_STATE(66)] = 503,
  [SMALL_STATE(67)] = 515,
  [SMALL_STATE(68)] = 527,
  [SMALL_STATE(69)] = 535,
  [SMALL_STATE(70)] = 547,
  [SMALL_STATE(71)] = 559,
  [SMALL_STATE(72)] = 571,
  [SMALL_STATE(73)] = 581,
  [SMALL_STATE(74)] = 593,
  [SMALL_STATE(75)] = 605,
  [SMALL_STATE(76)] = 613,
  [SMALL_STATE(77)] = 625,
  [SMALL_STATE(78)] = 637,
  [SMALL_STATE(79)] = 649,
  [SMALL_STATE(80)] = 661,
  [SMALL_STATE(81)] = 673,
  [SMALL_STATE(82)] = 685,
  [SMALL_STATE(83)] = 695,
  [SMALL_STATE(84)] = 705,
  [SMALL_STATE(85)] = 715,
  [SMALL_STATE(86)] = 725,
  [SMALL_STATE(87)] = 735,
  [SMALL_STATE(88)] = 745,
  [SMALL_STATE(89)] = 755,
  [SMALL_STATE(90)] = 762,
  [SMALL_STATE(91)] = 769,
  [SMALL_STATE(92)] = 776,
  [SMALL_STATE(93)] = 783,
  [SMALL_STATE(94)] = 790,
  [SMALL_STATE(95)] = 797,
  [SMALL_STATE(96)] = 804,
  [SMALL_STATE(97)] = 808,
  [SMALL_STATE(98)] = 812,
  [SMALL_STATE(99)] = 816,
  [SMALL_STATE(100)] = 820,
  [SMALL_STATE(101)] = 824,
  [SMALL_STATE(102)] = 828,
  [SMALL_STATE(103)] = 832,
  [SMALL_STATE(104)] = 836,
  [SMALL_STATE(105)] = 840,
  [SMALL_STATE(106)] = 844,
  [SMALL_STATE(107)] = 848,
  [SMALL_STATE(108)] = 852,
  [SMALL_STATE(109)] = 856,
  [SMALL_STATE(110)] = 860,
  [SMALL_STATE(111)] = 864,
  [SMALL_STATE(112)] = 868,
  [SMALL_STATE(113)] = 872,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(31),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(95),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(38),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(85),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(34),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(49),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(49),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 3),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 3),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binexpr, 3),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binexpr, 3),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if, 5),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if, 5),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iter, 5),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_iter, 5),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 5),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 5),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 4),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 4),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 4),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let, 5),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let, 5),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 2),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unaryexpr, 2),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unaryexpr, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_func_repeat1, 2), SHIFT_REPEAT(83),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [223] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_dyn(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
