[package]
name = "dyn-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2.0.4"
parser = { version = "0.1.0", path = "../parser" }
strum = { version = "0.25.0", features = ["derive"] }
